language: haskell

ghc:
    - 7.8
    - 7.6

before_install:
    - cabal install --only-dependencies --enable-tests --max-backjumps=-1 --reorder-goals

script:
    - cabal install --enable-tests xml-html-conduit-lens.cabal
    - cabal sdist
